markdown: redcarpet

title: Kevin Dungs
email: kevin@dun.gs
description: Kevin writes about programming and physics. Mostly programming, though.
baseurl: ""
url: "https://dun.gs"
twitter_username: kdungs
github_username:  kdungs
