base_url = "https://dun.gs"
compile_sass = true
build_search_index = false
taxonomies = []

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "OneHalfLight", filename = "syntax-theme.css" },
]
render_emoji = true

[extra]
